FROM python:3.11-slim

WORKDIR /app

COPY ./frontend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./frontend /app

CMD ["streamlit", "run", "home.py"]
