services:
  db:
    container_name: fast-async-db
    image: postgres:16
    restart: always
    volumes:
      - fast_async_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fast-async
      POSTGRES_USER: fast-async
      POSTGRES_PASSWORD: fast-async-pw
      PGDATA: /var/lib/postgresql/data/fast-async/
    ports:
      - "54320:5432"
  redis:
    image: redis:7.2.5
    container_name: fast-async-redis
    ports:
      - "63790:6379"

volumes:
  fast_async_db:
