services:
  db:
    container_name: chat-db
    image: postgres:16
    restart: always
    volumes:
      - chat_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat-pw
      PGDATA: /var/lib/postgresql/data/chat/
    ports:
      - "54320:5432"
  redis:
    image: redis:7.2.5
    container_name: chat-redis
    ports:
      - "63790:6379"

volumes:
  chat_db:
