"""Add UserRelation

Revision ID: ffc48f6d8251
Revises: 5f7a45cd4db2
Create Date: 2024-10-09 14:29:57.870170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc48f6d8251'
down_revision: Union[str, None] = '5f7a45cd4db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_user_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['service_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_user_relation')
    # ### end Alembic commands ###
