"""Add Chat

Revision ID: 9e0dbca6050a
Revises: 5f7a45cd4db2
Create Date: 2024-10-10 05:37:00.400950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e0dbca6050a'
down_revision: Union[str, None] = '5f7a45cd4db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Integer(), nullable=False),
    sa.Column('user_two_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), nullable=False),
    sa.CheckConstraint('user_one_id < user_two_id', name='user_one_less_than_user_two'),
    sa.ForeignKeyConstraint(['user_one_id'], ['service_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_two_id'], ['service_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uidx_chat_room_users')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['service_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages', 'chat_message', ['chat_room_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
